[project]
name = "pythonproject1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.17.0",
    "pydantic>=2.11.7",
    "ruff>=0.12.7",
]
